#!/usr/bin/env node

const fs = require('fs');
const {execSync} = require('child_process');

const json = JSON.parse(fs.readFileSync('./src/version.json').toString());
const pkg = JSON.parse(fs.readFileSync('./package.json').toString());

json.electron = execSync('./node_modules/.bin/electron --version').toString().trim().replace('v', '');
json.fulcrum = pkg.version;

fs.writeFileSync('./src/version.json', JSON.stringify(json));
fs.writeFileSync('./app/version.json', JSON.stringify(json));
