#!/usr/bin/env node

const fs = require('fs');

const json = JSON.parse(fs.readFileSync('./src/version.json').toString());
const pkg = JSON.parse(fs.readFileSync('./package.json').toString());

json.fulcrum = pkg.version;

fs.writeFileSync('./src/version.json', JSON.stringify(json));
// fs.writeFileSync('./package.json', JSON.stringify(pkg, null, '  '));
